Add backwards-compatibility for old sqlite cache files
Fixes

    Traceback (most recent call last):
      File "/opt/project-summary/summary.py", line 1705, in main
        print_html_report(projects, config, args.output_file)
      File "/opt/project-summary/summary.py", line 1750, in print_html_report
        html = template.render_unicode(
      File "/opt/project-summary/.venv/lib/python3.10/site-packages/mako/template.py", line 439, in render_unicode
        return runtime._render(
      File "/opt/project-summary/.venv/lib/python3.10/site-packages/mako/runtime.py", line 874, in _render
        _render_context(
      File "/opt/project-summary/.venv/lib/python3.10/site-packages/mako/runtime.py", line 916, in _render_context
        _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
      File "/opt/project-summary/.venv/lib/python3.10/site-packages/mako/runtime.py", line 938, in _exec_template
        _render_error(template, context, compat.exception_as())
      File "/opt/project-summary/.venv/lib/python3.10/site-packages/mako/runtime.py", line 948, in _render_error
        result = template.error_handler(context, error)
      File "/opt/project-summary/.venv/lib/python3.10/site-packages/mako/runtime.py", line 936, in _exec_template
        callable_(context, *args, **kwargs)
      File "memory:0x7fee631511b0", line 77, in render_body
        __M_writer(filters.html_escape(column.td(project)))
        # memory:0x7fee631511b0 line 110 in render_body:
        #                 ${column.td(project)}
      File "/opt/project-summary/summary.py", line 1097, in td
        self.inner_html(project),
      File "/opt/project-summary/summary.py", line 1391, in inner_html
        body=f'{project.downloads:,}' if project.downloads is not None else '-')
      File "/usr/lib/python3.10/functools.py", line 981, in __get__
        val = self.func(instance)
      File "/opt/project-summary/summary.py", line 821, in downloads
        data = self.cache.get(
      File "/opt/project-summary/summary.py", line 241, in get
        if expires is None or expires < now:
    TypeError: can't compare offset-naive and offset-aware datetimes